### ISSUE TITLE
Return an error on Windows 7

### ISSUE THREAD

**Issue by LuaChunk** [mixer/interactive-cpp#91]
Hi,

We've been using interactive V1. After upgrading to V2 we found that it doesn't run on Windows 7. This function is being called https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpwebsocketcompleteupgrade by interactive V2, which is only available on Win8 and above.

Is it intended that interactive V2 wont support Windows 7?

Regards,
Ryan.

**Comment by JoshSnider** [comment]
@LuaChunk This is by design. If you have a need to support Windows 7 with Mixer Interactive you may use the [legacy](https://github.com/mixer/interactive-cpp/tree/legacy) branch which has the V1 API intact.

One of the main design principles for V2 was to have no external library dependencies so that source can be dropped into any existing codebase. Unfortunately, Windows 7 does not have the required websocket support to allow this without a dependency on something like the [cpprestsdk](https://github.com/Microsoft/cpprestsdk).

**Comment by LuaChunk** [comment]
That's fine, but it's a hard crash on Win 7 because the DLL fails to load, which means no game can ever support interactive V2 if they intend to run on Win 7. interactive V2 should at least fail gracefully, return failure rather that hard crash the application.
